FROM python:3.9

# Install dependencies including libGL.so.1
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Install pip dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set working directory and copy app code
WORKDIR /app
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Run FastAPI application
CMD ["fastapi", "dev", "--host", "0.0.0.0", "api.py"]
